### ISSUE TITLE
Self healing

### ISSUE THREAD

**Issue by ShalokShalom** [lucaslorentz/caddy-run#4]
Has this self healing support?

**Comment by lucaslorentz** [comment]
No.
It can heal the processes it launches and supervise.
But if caddy itself crashes, it doesn't heal itself.

Maybe if you install caddy as a service you can setup it to be restarted after crash. Check the caddy service plugin, maybe it supports that: https://github.com/hacdias/caddy-service

Does that answer your question? If no, please, give me more details.

**Comment by ShalokShalom** [comment]
Partly. How does it heal the processes it launches? Automatically?

**Comment by lucaslorentz** [comment]
If the running process exits, the supervisor starts it again after 10 seconds, based on the setting `restart_policy`:
- **never**: never restart the process after it exits, regardless it's exit code
- **on_failure**: restart the process if the exit code is different than 0 (failure)
- **always**: always restart the process after it finishes

If after restarting the process, it exits again in less than 10 minutes, supervisor considers it unstable and increase it's restart delay to 20 seconds, if it fails again it increases to 40, and so forth. Whenever it runs for 10 minutes, the restart delay is reset to 10 seconds.

**Comment by ShalokShalom** [comment]
So every software that I put on Caddy can provide the same self healing capabilities as Erlang's VM?

**Comment by lucaslorentz** [comment]
Sorry, but I don't know how Erlang's VM healing works, so I can't compare.

**Comment by ShalokShalom** [comment]
I see, thanks a lot.

I think this feature is worth mentioning in your README anyways.

Good job :D
